// apps/frontend/shop/src/widgets/header/ui/header.svelte
<script>
  import { CartButton } from '~/entities/cart';
</script>

<header class="sticky top-0 z-50 bg-background h-14 flex items-center border-b border-divider/50">
  <div class="container mx-auto px-4 flex items-center justify-between">
    <a href="/" class="text-lg font-bold">
      <h1 class="text-lg font-bold">Light Shop</h1>
    </a>
    <CartButton />
  </div>
</header>

// apps/frontend/admin-panel/src/features/header/ui/Header.tsx
import { useLocation, useNavigate } from '@tanstack/react-router'
import { HEADER_PATHS } from '../model/header-paths'
import { LinkButton } from '@/shared/ui/link-button'
import { cn } from '@/shared/lib/utils'
import { Button } from '@/shared/ui/button'
import { useSession } from '@/shared/model/session'

export function Header() {
  const { href } = useLocation()
  const { logout } = useSession()
  const navigate = useNavigate()

  return (
    <header className="flex sticky top-0 z-10 bg-background items-center justify-between h-14 shrink-0 border-b border-border px-4">
      <div className="flex items-center gap-8">
        <h1 className="text-lg font-bold">Light Shop Admin</h1>
        <div className="flex items-center gap-2">
          {HEADER_PATHS.map((path) => (
            <LinkButton
              variant="ghost"
              size="sm"
              key={path.path}
              to={path.path}
              className={cn(href !== path.path && 'opacity-50')}
            >
              {path.label}
            </LinkButton>
          ))}
        </div>
      </div>
      <div className="flex items-center gap-2">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => {
            logout()
            navigate({ to: '/auth/sign-in' })
          }}
        >
          Logout
        </Button>
      </div>
    </header>
  )
}
